version: '3.7'
services:
  api:
    image: "node:18.15-buster"
    build: .
    container_name: "node-project"
    command: sh -c "sleep 6 && npm i && npx prisma migrate dev && npm run start:dev"
    ports:
      - "3333:3333"
      - "5555:5555"
    volumes:
      - ../:/api
    working_dir: /api/
    tty: true
    stdin_open: true
    networks:
      api-db-network:
        ipv4_address: 172.28.0.2
    depends_on:
      - api-solid-pg

  api-solid-pg:
    image: bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=ignitenode03
    volumes:
      - ../database:/var/lib/mysql
    
    networks:
      api-db-network:
        ipv4_address: 172.28.0.3


networks:
  api-db-network:
    driver: bridge
    ipam:
      config:
        - subnet: "172.28.0.0/16"
          gateway: "172.28.5.254"